- name: Install App Server
  hosts: prod
  become: True 
  tasks:
    - name: Install App Server
      ansible.builtin.yum:
        name: httpd
        state: latest 

    - name: Start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes